volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:

networks:
  demo:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['demo']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - OLLAMA_HOST=${OLLAMA_HOST:-ollama:11434}
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    - N8N_TRUST_PROXY=true
    - N8N_PUSH_BACKEND=sse
    - WEBHOOK_URL=https://${CODESPACE_NAME:-localhost}-5678.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}/
    - N8N_HOST=${CODESPACE_NAME:-localhost}-5678.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}
    - N8N_PROTOCOL=https
    - N8N_DISABLE_PUSH_ORIGIN_CHECK=true
    - N8N_SKIP_ORIGIN_CHECK=true
  env_file:
    - path: .env
      required: true

x-ollama: &service-ollama
  image: alpine/ollama:latest
  networks: ['demo']
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: alpine/ollama:latest
  networks: ['demo']
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  environment:
    - OLLAMA_HOST=ollama:11434
  command:
    - "echo 'Waiting for Ollama to be ready...' && until ollama list >/dev/null 2>&1; do sleep 1; done && echo 'Ollama is ready, pulling llama3.2...' && ollama pull llama3.2"

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks: ['demo']
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
    - "-c"
    - |
      if [ -z "$(n8n list:workflow --onlyId)" ]; then
        n8n import:credentials --separate --input=/demo-data/credentials && \
        n8n import:workflow --separate --input=/demo-data/workflows
      else
        echo "Workflows exist, skipping import"
      fi
    volumes:
      - ./n8n/demo-data:/demo-data
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/demo-data:/demo-data
      - ./shared:/data/shared
      - .:/workspaces/bpi-n8n-esnsaas:cached
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    <<: *service-ollama
    container_name: ollama

  ollama-pull-llama:
    <<: *init-ollama
    container_name: ollama-pull-llama
    depends_on:
      - ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-gpu-amd:
    profiles: ["gpu-amd"]
    <<: *service-ollama
    image: ollama/ollama:rocm
    devices:
      - "/dev/kfd"
      - "/dev/dri"

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu

  ollama-pull-llama-gpu-amd:
    profiles: [gpu-amd]
    <<: *init-ollama
    image: ollama/ollama:rocm
    depends_on:
     - ollama-gpu-amd

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    container_name: devcontainer
    volumes:
      - .:/workspaces/bpi-n8n-esnsaas:cached
    networks:
      - demo
    command: /bin/sh -c "while sleep 1000; do :; done"
